REGION_DISTRICT = (
    ("Northern Region", "Abim District"),
    ("Northern Region", "Adjumani District"),
    ("Northern Region", "Agago District"),
    ("Northern Region", "Alebtong District"),
    ("Northern Region", "Amolatar District"),
    ("Northern Region", "Amudat District"),
    ("Eastern Region", "Amuria District"),
    ("Northern Region", "Amuru District"),
    ("Northern Region", "Apac District"),
    ("Northern Region", "Arua District"),
    ("Eastern Region", "Budaka District"),
    ("Eastern Region", "Bududa District"),
    ("Eastern Region", "Bugiri District"),
    ("Eastern Region", "Bugweri District"),
    ("Western Region", "Buhweju District"),
    ("Central Region", "Buikwe District"),
    ("Eastern Region", "Bukedea District"),
    ("Central Region", "Bukomansimbi District"),
    ("Eastern Region", "Bukwo District"),
    ("Eastern Region", "Bulambuli District"),
    ("Western Region", "Buliisa District"),
    ("Western Region", "Bundibugyo District"),
    ("Western Region", "Bunyangabu District"),
    ("Western Region", "Bushenyi District"),
    ("Eastern Region", "Busia District"),
    ("Eastern Region", "Butaleja District"),
    ("Central Region", "Butambala District"),
    ("Eastern Region", "Butebo District"),
    ("Central Region", "Buvuma District"),
    ("Eastern Region", "Buyende District"),
    ("Northern Region", "Dokolo District"),
    ("Central Region", "Gomba District"),
    ("Northern Region", "Gulu District"),
    ("Western Region", "Hoima District"),
    ("Western Region", "Ibanda District"),
    ("Eastern Region", "Iganga District"),
    ("Western Region", "Isingiro District"),
    ("Eastern Region", "Jinja District"),
    ("Northern Region", "Kaabong District"),
    ("Western Region", "Kabale District"),
    ("Western Region", "Kabarole District"),
    ("Eastern Region", "Kaberamaido District"),
    ("Western Region", "Kagadi District"),
    ("Western Region", "Kakumiro District"),
    ("Central Region", "Kalangala District"),
    ("Eastern Region", "Kaliro District"),
    ("Central Region", "Kalungu District"),
    ("Central Region", "Kampala District"),
    ("Eastern Region", "Kamuli District"),
    ("Western Region", "Kamwenge District"),
    ("Western Region", "Kanungu District"),
    ("Eastern Region", "Kapchorwa District"),
    ("Eastern Region", "Kapelebyong District"),
    ("Western Region", "Kasese District"),
    ("Central Region", "Kassanda District"),
    ("Eastern Region", "Katakwi District"),
    ("Central Region", "Kayunga District"),
    ("Western Region", "Kibaale District"),
    ("Central Region", "Kiboga District"),
    ("Eastern Region", "Kibuku District"),
    ("Western Region", "Kikuube District"),
    ("Western Region", "Kiruhura District"),
    ("Western Region", "Kiryandongo District"),
    ("Western Region", "Kisoro District"),
    ("Northern Region", "Kitgum District"),
    ("Northern Region", "Koboko District"),
    ("Northern Region", "Kole District"),
    ("Northern Region", "Kotido District"),
    ("Eastern Region", "Kumi District"),
    ("Northern Region", "Kwania District"),
    ("Eastern Region", "Kween District"),
    ("Central Region", "Kyankwanzi District"),
    ("Western Region", "Kyegegwa District"),
    ("Western Region", "Kyenjojo District"),
    ("Central Region", "Kyotera District"),
    ("Northern Region", "Lamwo District"),
    ("Northern Region", "Lira District"),
    ("Eastern Region", "Luuka District"),
    ("Central Region", "Luwero District"),
    ("Central Region", "Lwengo District"),
    ("Central Region", "Lyantonde District"),
    ("Eastern Region", "Manafwa District"),
    ("Northern Region", "Maracha District"),
    ("Central Region", "Masaka District"),
    ("Western Region", "Masindi District"),
    ("Eastern Region", "Mayuge District"),
    ("Eastern Region", "Mbale District"),
    ("Eastern Region", "Mbale District"),
    ("Western Region", "Mbarara District"),
    ("Western Region", "Mitooma District"),
    ("Central Region", "Mityana District"),
    ("Northern Region", "Moroto District"),
    ("Northern Region", "Moyo District"),
    ("Central Region", "Mpigi District"),
    ("Central Region", "Mubende District"),
    ("Central Region", "Mukono District"),
    ("Northern Region", "Nabilatuk District"),
    ("Northern Region", "Nakapiripirit District"),
    ("Central Region", "Nakaseke District"),
    ("Central Region", "Nakasongola District"),
    ("Eastern Region", "Namayingo District"),
    ("Eastern Region", "Namisindwa District"),
    ("Eastern Region", "Namutumba District"),
    ("Northern Region", "Napak District"),
    ("Northern Region", "Nebbi District"),
    ("Eastern Region", "Ngora District"),
    ("Western Region", "Ntoroko District"),
    ("Western Region", "Ntungamo District"),
    ("Northern Region", "Nwoya District"),
    ("Northern Region", "Omoro District"),
    ("Northern Region", "Otuke District"),
    ("Northern Region", "Oyam District"),
    ("Northern Region", "Pader District"),
    ("Northern Region", "Pakwach District"),
    ("Eastern Region", "Pallisa District"),
    ("Central Region", "Rakai District"),
    ("Western Region", "Rubanda District"),
    ("Western Region", "Rubirizi District"),
    ("Western Region", "Rukiga District"),
    ("Western Region", "Rukungiri District"),
    ("Central Region", "Sembabule District"),
    ("Eastern Region", "Serere District"),
    ("Western Region", "Sheema District"),
    ("Eastern Region", "Sironko District"),
    ("Eastern Region", "Soroti District"),
    ("Eastern Region", "Tororo District"),
    ("Central Region", "Wakiso District"),
    ("Northern Region", "Yumbe District"),
    ("Northern Region", "Zombo District"),
)

DISTRICT_REGION = { d:r for r,d in REGION_DISTRICT }

SUBREGION_REGION = {
	'Acholi': 'Northern Region',
	'Ankole': 'Western Region',
	'Bugisu': 'Eastern Region',
	'Bukedi': 'Eastern Region',
	'Bunyoro': 'Western Region',
	'Busoga': 'Eastern Region',
	'Kampala': 'Central Region',
	'Karamoja': 'Northern Region',
	'Kigezi': 'Western Region',
	'Lango': 'Northern Region',
	'North Central': 'Central Region',
	'South Central': 'Central Region',
	'Teso': 'Eastern Region',
	'Tooro': 'Western Region',
	'West Nile': 'Northern Region',
}
